[project]
name = "gaming-the-answer-matcher"
version = "0.1.0"
description = "A multimodal question-answering assistant combining vision and language models."
authors = [
    "Kevork Sulahian <kevorkysulahian@gmail.com>"
]
requires-python = ">=3.8"

[project.dependencies]
packaging = ">=23.0"
addict = ">=2.4.0"
editdistance = ">=0.6.2"
einops = ">=0.7.0"
fairscale = ">=0.4.0"
jsonlines = ">=4.0.0"
markdown2 = ">=2.4.0"
matplotlib = ">=3.7.0"
more-itertools = ">=10.0.0"
nltk = ">=3.8.0"
numpy = ">=1.24.0"
opencv-python-headless = ">=4.5.5"
openpyxl = ">=3.1.0"
Pillow = ">=10.0.0"
sacrebleu = ">=2.3.0"
seaborn = ">=0.13.0"
shortuuid = ">=1.0.0"
spacy = ">=3.5.0"
timm = ">=0.9.0"
torch = ">=2.0.0"
torchvision = ">=0.16.0"
tqdm = ">=4.66.0"
protobuf = ">=4.25.0"
transformers = ">=4.40.0"
typing_extensions = ">=4.8.0"
uvicorn = ">=0.24.0"
socksio = ">=1.0.0"
gradio = ">=3.24.0"
gradio_client = ">=0.0.8"
wandb = ">=0.15.0"
